---
- name: Production Host Setup
  hosts: all
  pre_tasks:
    - name: Include setup.yml
      include: setup.yml

  tasks:
    - name: Include Nginx
      tags: nginx
      include: nginx.yml
      notify: Restart Nginx
      
    - name: Include Firewalld
      include: firewalld.yml
      notify:
        - Reload Firewalld

    - name: Include Fail2ban
      tags: fail2ban
      include: fail2ban.yml
      notify: 
        - Restart Fail2ban

    - name: Include Docker
      tags: docker
      include: docker.yml

  handlers:
    - name: Restart Fail2ban
      service:
        name: fail2ban
        state: restarted

    - name: Reload Firewalld
      command: firewall-cmd --reload

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Reload sshd
      service:
        name: sshd
        state: reloaded
