---
- hosts: webserver

  pre_tasks:

    - name: Update Repository Index
      dnf:
        update_cache: true
        update_only: true

  roles:
    - webserver

- import_playbook: common.yml 
  vars: 
    CURRENT_HOSTS: webserver
