---
- name: Install Packages
  yum:
    name: 
      - ansible
      - fail2ban
      - firewalld
      - git
      - golang
      - nginx
      - nmap
      - policycoreutils-devel
      - ranger
      - vim
    state: latest
