---
- name: Clone Repositories
  vars:
    github: 
      - { repo: "{{ git_control_jynx_dev }}", dest: /jynx/control }
      - { repo: "{{ git_jynx_dev }}", dest: /jynx/dev }

  git:
    repo: "{{ item[1].repo }}"
    dest: "/home/{{ item[0] }}{{ item[1].dest }}"
    clone: yes 
    key_file: "/home/{{ item[0] }}/.ssh/github"
    ssh_opts: "-o ForwardAgent=yes"
  with_nested: 
    - "{{ users }}"
    - "{{ github }}"
  register: clone

- name: Chown Working Dir
  file:
    state: directory
    setype: user_home_t
    owner: "{{ item }}"
    group: "{{ item }}"
    path: "/home/{{ item }}/jynx"
    recurse: true
  loop: 
    "{{ users }}"
  when: clone.changed
  
