---
  - name: Start Fail2ban
    service:
      name: fail2ban
      enabled: true
      state: started
  
  - name: Setup Conf
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - { src: jail.local, dest: /etc/fail2ban/jail.local }
      - { src: sshd.conf, dest: /etc/fail2ban/jail.d/sshd.conf }
    notify: Restart Fail2ban
